### PR TITLE
W-10547474: add constructor to parametrize DialectInstance parsing guessing

### PR DESCRIPTION
**Pull request by tomsfernandez**

### CODE REVIEW

**Comment by uip-robot-zz** [comment]
Git2Gus App is installed but the `.git2gus/config.json` doesn't exist.

**Comment by nschejtman** [comment]
Why are you parametrizing the Guess? Guesses are Instance specific

Plugins should create Guesses based on wether they can parse an instance or not. You are parametrizing the creation of a Parsing Plugin based on a Guess that should be created by the plugin itself

**Comment by tomsfernandez** [comment]
@nschejtman yes, guesses are instance specific but they rely on the AST to check wether an AST can be parsed by said dialect. I want to be able to parametrize the Guess so that given an AST it ALWAYS applies to my Dialect.

I can't just override the applies method as the guess is also used in Parsing

**Comment by tomsfernandez** [comment]
I guess I could make a plugin from scratch but I'd like to avoid recoding as much of the plugin as possible

**Comment by nschejtman** [comment]
TBH I don't like this. Guesses are Instance specific, Plugin are not. They should apply to any instance. It's like having a dedicated RAML Plugin for every RAML API.

Since the Guess is what determines the `applies` method of this plugin, you are fixing the result the the `applies` on at plugin creation time.

**Review by nschejtman — DISMISSED** [review]

**Review by nschejtman — APPROVED** [review]

**Pull request merged**
